---

- name: Restart PVR
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/docker-pvr/"
    build: false
    restarted: true
  become: false

- name: Restart VPN
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/docker-vpn/"
    build: false
    restarted: true
  become: false